config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'users/sessions'
  } 

  root to: "home#top"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :plates do
    resources :warehouses, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hardness.rb
class Hardness < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '15' },
    { id: 3, name: '30' },
    { id: 4, name: '36' },
    { id: 5, name: '40' },
    { id: 6, name: '50' },
    { id: 7, name: '60' },
    { id: 8, name: '70' },
    { id: 9, name: '80' },
    { id: 10, name: '100' },
    { id: 11, name: '150' },
    { id: 12, name: '180' },
    { id: 13, name: '200' },
    { id: 14, name: '250' },
    { id: 15, name: '300' },
    { id: 16, name: '1000' },
    { id: 17, name: '1500' },
    { id: 18, name: '2000' },
    { id: 19, name: '2500' },
    { id: 20, name: '3000' },
    { id: 21, name: '3500' },
    { id: 22, name: '4000' },
    { id: 23, name: '4500' },
    { id: 24, name: '5000' },
    { id: 25, name: '5500' }
  ]
end

app/models/mold.rb
class Mold < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'A' },
    { id: 3, name: 'ASW' },
    { id: 4, name: 'ASS' },
    { id: 5, name: 'E' },
    { id: 6, name: 'SC' },
    { id: 7, name: 'TC' }
  ]
end

app/models/plate.rb
class Plate < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :mold
  belongs_to_active_hash :thickness
  belongs_to_active_hash :hardness
  belongs_to_active_hash :plate_color
  belongs_to_active_hash :plate_width
  belongs_to_active_hash :plate_length

  belongs_to :user
  has_many :warehouses, dependent: :destroy

  with_options presence: true do
    validates :mold_id, :thickness_id, :hardness_id,
              :plate_color, :plate_width, :plate_length
    validates :number_of_sheets, format: { with: /\A[0-9]+\z/ }
  end

  with_options numericality: { other_than: 1 } do
    validates :mold_id
    validates :thickness_id
    validates :hardness_id
    validates :plate_color_id
    validates :plate_width_id
    validates :plate_length_id
  end
end

app/models/plate_color.rb
class PlateColor < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'N' },
    { id: 3, name: 'BK-AD' },
    { id: 4, name: 'BK-AC' },
    { id: 5, name: 'SBL' },
    { id: 6, name: 'GR' },
    { id: 7, name: 'GY' },
    { id: 8, name: 'WH' },
    { id: 9, name: 'Y' },
    { id: 10, name: 'BL' },
    { id: 11, name: 'ｱｲﾎﾞﾘｰ' }
  ]
end

app/models/plate_length.rb
class PlateLength < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1000' },
    { id: 3, name: '1500' },
    { id: 4, name: '1700' },
    { id: 5, name: '1800' },
    { id: 6, name: '1820' },
    { id: 7, name: '1900' },
    { id: 8, name: '2000' },
    { id: 9, name: '2100' },
    { id: 10, name: '2200' },
    { id: 11, name: '2300' },
    { id: 12, name: '2310' },
    { id: 13, name: '2400' },
    { id: 14, name: '2500' }
  ]
end

app/models/plate_width.rb
class PlateWidth < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '800' },
    { id: 3, name: '860' },
    { id: 4, name: '900' },
    { id: 5, name: '910' },
    { id: 6, name: '1000' },
    { id: 7, name: '1150' },
    { id: 8, name: '1200' },
    { id: 9, name: '1250' },
    { id: 10, name: '1300' },
    { id: 11, name: '1400' },
    { id: 12, name: '1600' }
  ]
end

app/models/thickness.rb
class Thickness < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1.5' },
    { id: 3, name: '2' },
    { id: 4, name: '3' },
    { id: 5, name: '4' },
    { id: 6, name: '5' },
    { id: 7, name: '6.5' },
    { id: 8, name: '7' },
    { id: 9, name: '9' },
    { id: 10, name: '10' },
    { id: 11, name: '12' },
    { id: 12, name: '20' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
         authentication_keys: [:name, :employee_number]

  has_many :plates
  has_many :warehouses

  with_options presence: true do
    validates :name
    validates :employee_number, uniqueness: true
    PASSWORD_REGEX = /\A[a-z\d]{6,}+\z/i.freeze
    validates :password, format: { with: PASSWORD_REGEX }
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  def self.guest
    find_or_create_by!(name:"テストユーザー", employee_number:"0000") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  belongs_to :user
  belongs_to :plate

  with_options presence: true do
    validates :warehouse_number, :warehouse_colum,
              :house_number, :number_of_stage
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :employee_number])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @users = User.all
    @plate = Plate.all
    @warehouse = Warehouse.all.order(id: 'DESC')
  end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  def index
    @plate = Plate.all.order(id: 'DESC')
  end

  def new
    @plate = Plate.new
  end

  def create
    @plate = Plate.new(plate_params)
    if @plate.save
      redirect_to plates_path, notice: 'プレート情報が登録されました'
    else
      render :new
    end
  end

  def edit
    @plate = Plate.find(params[:id])
  end

  def update
    @plate = Plate.find(params[:id])
    if @plate.update(plate_params)
      flash[:notice] = '編集が完了しました'
      redirect_to action: :index
    else
      flash[:alert] = '編集が失敗しました'
      render action: :edit
    end
  end

  def destroy
    plate = Plate.find(params[:id])
    if plate.destroy
      flash[:notice] = '削除が完了しました'
      redirect_to action: :index
    else
      flash[:alert] = '削除が失敗しました'
      render :index
    end
  end

  private

  def plate_params
    params.require(:plate).permit(:mold_id, :thickness_id, :hardness_id, :plate_color_id,
                                  :plate_width_id, :plate_length_id, :number_of_sheets).merge(user_id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: '閲覧ありがとうございます！ゲストユーザーとしてログインしました。'
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_plate, only: [:new, :create]

  def index
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
      flash[:notice] = '登録が完了しました'
      redirect_to plates_path(@plate)
    else
      flash[:alert] = '登録に失敗しました'
      render :new
    end
  end

  private

  def set_plate
    @plate = Plate.find(params[:plate_id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:warehouse_number, :warehouse_colum, :house_number, :number_of_stage).merge(user_id: current_user.id, plate_id: @plate.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/home/top.html.erb
<div class="container-fluid">
  <div class="img-fluid">
    <h1 class="title">Warehouse</h1>
    <div class="d-flex justify-content-around">
    <% if user_signed_in? %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-warning btn-lg" %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path, class: "btn btn-primary btn-lg" %>
      <%= link_to 'ログイン', new_user_session_path, class: "btn btn-info btn-lg" %></li>
      <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "btn btn-success btn-lg" %></li>
    <% end %>
    </div>
  </div>
  <%#以下はログイン状態じゃないと表示されない%>
  <% if user_signed_in? %>
  <div class="contents">
    <h2 class="contents-title">メインメニュー</h2>
    <div class="content">
      <h3 class='service-explain'>
        <%= link_to "商品の登録・倉庫への登録", plates_path, class:"btn-shadow btn btn-primary btn-lg" %>
      </h3>
    </div>
    <div class="content">
      <h3 class="service-explain">
        <% link_to "倉庫内検索", "#", class:"btn-shadow btn btn-primary btn-lg" %>
      </h3>
    </div>
    <div class="content">
      <h3 class="service-explain">
        <% link_to "検索履歴", "#", class:"btn-shadow btn btn-primary btn-lg" %>
      </h3>
    </div>
  </div>
  <% end %>
  <div class="contents">
    <h2 class="contents-title">プレート一覧</h2>
    <table class="table-striped">
    <tr>
      <th>型</th><th>厚み</th><th>硬さ</th><th>色</th><th>幅</th><th>長さ</th><th>枚数</th>
      <th>倉庫名</th><th>列</th><th>番地</th><th>段数</th>
      <th>登録者</th>
    </tr>
    <% @warehouse.each do |warehouse| %>
    <tr>  
      <td><%= warehouse.plate.mold.name %></td>
      <td><%= warehouse.plate.thickness.name %></td>
      <td><%= warehouse.plate.hardness.name %></td>
      <td><%= warehouse.plate.plate_color.name %></td>
      <td><%= warehouse.plate.plate_width.name %></td>
      <td><%= warehouse.plate.plate_length.name %></td>
      <td><%= warehouse.plate.number_of_sheets %></td>
      <td>第<%= warehouse.warehouse_number %>倉庫</td>
      <td><%= warehouse.warehouse_colum %>列</td>
      <td><%= warehouse.house_number %>番地</td>
      <td><%= warehouse.number_of_stage %>段目</td>
      <td><%= warehouse.user.name %></td>
    </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Warehouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-primary lert-dismissible fade show"<%= message_type %>"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
    <%= render "shared/footer" %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/plates/edit.html.erb
<%= form_with model: @plate, url:plate_path, local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">プレート編集</h1>
  </div>
  <div class="form-group">
  <%= render 'shared/error_messages', model: f.object %>
    <div class="form-text-wrap">
      <label class="form-text">型
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:mold_id, Mold.all, :id, :name, {}, {class:"form-control", id:"plate-mold"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">厚み
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:thickness_id, Thickness.all, :id, :name, {}, {class:"form-control", id:"plate-thickness"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">硬さ
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:hardness_id, Hardness.all, :id, :name, {}, {class:"form-control", id:"plate-hardness"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">色
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_color_id, PlateColor.all, :id, :name, {}, {class:"form-control", id:"plate-color"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">幅
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_width_id, PlateWidth.all, :id, :name, {}, {class:"form-control", id:"plate-width"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">長さ
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_length_id, PlateLength.all, :id, :name, {}, {class:"form-control", id:"plate-length"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">枚数(半角数字のみ)
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :number_of_sheets, class:"form-control", id:"plate_number_of_sheets" %>
  </div>
  <div class="form-footer">
    <h2 class='form-footer-text'>
      記入項目を確認後<br>ボタンを押してください
    </h2>
    <div class="register-btn">
      <%= f.submit "登録する" ,class:"btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<% end %>

app/views/plates/index.html.erb
<div class="container-fluid">
  <div class="plate-registration">
    <div class="plate-registration-title">プレートへの登録はこちら
    </div>
    <%= link_to "新規登録", new_plate_path, class:"btn-shadow btn btn-primary btn-lg" %>
  </div>
  <div class="plate-index">
    <div class="plate-index-title">プレート登録一覧</div>
    <% @plate.each do |plate| %>
    <% if current_user.name == plate.user.name %>
    <div class="plate-contents">
      <div class="plate-content">
        <%= plate.mold.name %>-<%= plate.thickness.name %>-<%= plate.hardness.name %> <%= plate.plate_color.name %> <%= plate.plate_width.name %>x<%= plate.plate_length.name %> <%= plate.number_of_sheets %>枚
      </div>
      <div class="plate-content-links">
        <% if plate.warehouses.blank? %>
          <%= link_to "倉庫へ登録", new_plate_warehouse_path(plate.id), class: "link-btn" %>
        <% end %>
          <%= link_to "編集", edit_plate_path(plate.id), method: :get, class: "link-btn" %>
          <%= link_to "削除", plate_path(plate.id), method: :delete, class: "link-btn" %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/plates/new.html.erb
<%= form_with model: @plate, url:plates_path, local: true do |f| %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">プレート登録</h1>
  </div>
  <div class="form-group">
  <%= render 'shared/error_messages', model: f.object %>
    <div class="form-text-wrap">
      <label class="form-text">型
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:mold_id, Mold.all, :id, :name, {}, {class:"form-control", id:"plate-mold"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">厚み
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:thickness_id, Thickness.all, :id, :name, {}, {class:"form-control", id:"plate-thickness"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">硬さ<span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:hardness_id, Hardness.all, :id, :name, {}, {class:"form-control", id:"plate-hardness"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">色<span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_color_id, PlateColor.all, :id, :name, {}, {class:"form-control", id:"plate-color"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">幅<span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_width_id, PlateWidth.all, :id, :name, {}, {class:"form-control", id:"plate-width"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">長さ<span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.collection_select(:plate_length_id, PlateLength.all, :id, :name, {}, {class:"form-control", id:"plate-length"}) %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">枚数(半角数字のみ)<span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :number_of_sheets, class:"form-control", id:"plate_number_of_sheets" %>
  </div>
  <div class="form-footer">
    <h2 class='form-footer-text'>
      記入項目を確認後<br>ボタンを押してください
    </h2>

    <div class="register-btn">
      <%= f.submit "登録する" ,class:"btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer py-5">
  <div class="row">
    <div class="col-12 col-md">
      <%= link_to image_tag( "home-icon.png", class:"footer-home-icon",),"/" %>
      <%= link_to "Warehouse", "/", class:"footer-service-title" %>
      <small class="d-block mb-3 text-muted">&copy;NORTH PADDY inc<br>2020-</small>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark m-10 ">
  <%= link_to image_tag( "home-icon.png", class:"d-inline-block align-top"),"/" %>
  <a class="navbar-brand mb-0 h1" href="/">Warehouse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">トップページ <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-employee">社員番号：<%= current_user.employee_number %></li>
      <li class="nav-user">氏名：<%= current_user.name %></li>
      <li> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          メニュー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a><%= link_to "プレート情報", plates_path, class: "dropdown-item" %></a>
          <a><%= link_to "プレート新規登録", new_plate_path, class: "dropdown-item" %> </a>
        </div>
      </li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "nav-link" %></li>
      <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "nav-link" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>
</header>

app/views/warehouses/new.html.erb
<%= form_with model:@warehouse, url:plate_warehouses_path, local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
<div class="form-wrap">
  <div class="form-header">
    <h1 class="form-header-text">倉庫に登録</h1>
    <div class="plate-information">
    <%= @plate.mold.name %>-<%= @plate.thickness.name %>-<%= @plate.hardness.name %> <%= @plate.plate_color.name %> 
    <%= @plate.plate_width.name %>x<%= @plate.plate_length.name %> <%= @plate.number_of_sheets %>枚 
    </div>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">倉庫NO.
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :warehouse_number, class:"form-control", id:"warehouse_number", placeholder:"例）1" %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">列
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :warehouse_colum, class:"form-control", id:"warehouse_colum", placeholder:"例）1" %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">番地
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :house_number, class:"form-control", id:"house_number",placeholder:"例）1" %>
  </div>
  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">段数
        <span class="badge badge-danger">必須</span>
      </label>
    </div>
    <%= f.text_field :number_of_stage, class:"form-control", id:"number_of_stage", placeholder:"例）1" %>
  </div>
  <div class="form-footer">
    <h2 class='form-footer-text'>
      記入項目を確認後<br>ボタンを押してください
    </h2>
    <div class="register-btn">
      <%= f.submit "登録する" ,class:"btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<% end %>